name: Build npm Package

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          submodules: true

      - uses: actions/setup-node@v6
        with:
          node-version: "24"
          cache: "npm"

      - uses: ./.github/actions/setup

      - run: npm ci

      - name: Package
        run: npm pack

      - name: Upload Archive
        uses: actions/upload-artifact@v6
        with:
          name: igf.tgz
          path: build/igf-*.tgz
