name: Build npm Package

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          submodules: true

      - uses: ./.github/actions/setup

      - name: Install and build
        run: |
          npm ci
          npm ci --prefix agent
          npm ci --prefix gui

      - name: Package
        run: npm pack

      - name: Upload Archive
        uses: actions/upload-artifact@v6
        with:
          name: igf.tgz
          path: igf-*.tgz
