name: Build Single Executable Tool

on:
  workflow_dispatch:

jobs:
  build:
    # todo: runs on new git tags
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Create directories
        run: mkdir -p build/Release agent/dist gui/dist

      - name: Install dependencies
        run: |
          bun install
          bun run install:bun

      - name: Build Cross
        run: bun run build:cross

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: builds
          path: |
            build/Release/
