name: Build npm Package

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          submodules: true

      - uses: actions/setup-node@v6
        with:
          node-version: "24"
          cache: "npm"

      - uses: ./.github/actions/setup

      - name: Install and build
        run: |
          npm ci
          cd agent && npm i && npm run build && cd ..
          cd gui && npm i && npm run build

      - name: Package
        run: npm pack

      - name: Upload Archive
        uses: actions/upload-artifact@v6
        with:
          name: igf.tgz
          path: igf-*.tgz
