name: ci

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    env:
      # workaround for building frontend
      NODE_OPTIONS: --openssl-legacy-provider

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependency
        run: npm ci

      - name: CI
        run: npm run prepublishOnly
