name: npm package

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          submodules: true

      - uses: actions/setup-node@v6
        with:
          node-version: "24"
          registry-url: 'https://registry.npmjs.org'
          cache: "npm"

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Reset node_modules
        run: rm -rf node_modules

      - run: npm ci

      - name: Package
        run: npm pack

      - name: Upload Archive
        uses: actions/upload-artifact@v6
        with:
          name: igf.tgz
          path: build/igf-*.tgz

      - name: Publish to npm
        if: ${{ !contains(github.ref, 'alpha') && !contains(github.ref, 'beta') }}
        run: npm publish

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          prerelease: ${{ contains(github.ref, 'beta') || contains(github.ref, 'alpha') }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
